apiVersion: v1
kind: Pod
metadata:
  name: app300-pod
  labels:
    name: app300
spec:
  containers:
  - name: app300-nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"